---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-kubernetes-runtime-config
spec:
  serviceAccountTemplate:
    metadata:
      name: crossplane-kubernetes-provider

---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
spec:
  package: xpkg.upbound.io/upbound/provider-kubernetes:v0.18.0
  runtimeConfigRef:
    name: provider-kubernetes-runtime-config
